const Role = {
    ADMIN: 'ADMIN',
    REGIONAL_HEAD: 'REGIONAL_HEAD',
    PROJECT_LEAD: 'PROJECT_LEAD',
    TEAM_LEAD: 'TEAM_LEAD',
    SENIOR_DEVELOPER: 'SENIOR_DEVELOPER',
    JUNIOR_DEVELOPER: 'JUNIOR_DEVELOPER',
    EMPLOYEE: 'EMPLOYEE',
    STUDENT: 'STUDENT',
    INTERN: 'INTERN',
}
export default Role;