const SkillCategory = {
    TECHNOLOGY: 'TECHNOLOGY',
    SOLUTION_ENGINEERING: 'SOLUTION_ENGINEERING',
    SELF_MANAGEMENT: 'SELF_MANAGEMENT',
    COMMUNICATION_SKILLS: 'COMMUNICATION_SKILLS',
    EMPLOYEE_LEADERSHIP: 'EMPLOYEE_LEADERSHIP',
}
export default SkillCategory;