name: Deploy MERN Application

on:
  push:
    branches:
      - 99-realease-branch-via-aws

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: lucatum/nodejs-app-aws-backend:latest
      
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: lucatum/nodejs-app-aws-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Pull latest images
        run: |
          docker pull lucatum/nodejs-app-aws-backend:latest
          docker pull lucatum/nodejs-app-aws-frontend:latest
      
      - name: Debug information
        run: |
          echo "Current directory: $(pwd)"
          echo "Docker version: $(docker --version)"
          echo "Docker images:"
          docker images
          echo "Running containers:"
          docker ps -a
      
      - name: Stop and remove existing containers
        run: |
          docker stop nodejs-app-backend nodejs-app-frontend || true
          docker rm nodejs-app-backend nodejs-app-frontend || true
      
      - name: Run backend container
        run: |
          echo "Attempting to run backend container"
          echo "Image name: lucatum/nodejs-app-aws-backend:latest"
          docker images
          docker run -d --name nodejs-app-backend \
            -p 3001:3001 \
            -e MONGO_URL='${{ secrets.MONGO_URL }}' \
            -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
            lucatum/nodejs-app-aws-backend:latest
          echo "Backend container started"
          docker ps
      
      - name: Run frontend container
        run: |
          echo "Attempting to run frontend container"
          echo "Image name: lucatum/nodejs-app-aws-frontend:latest"
          docker run -d --name nodejs-app-frontend \
            -p 80:80 \
            -e REACT_APP_API_BASE_URL=http://${{ secrets.EC2_PUBLIC_IP }}:3001/api \
            lucatum/nodejs-app-aws-frontend:latest
          echo "Frontend container started"
          docker ps
      
      - name: Cleanup old images
        run: docker image prune -af

      - name: Final deployment status
        run: |
          echo "Deployment completed"
          echo "Running containers:"
          docker ps
          echo "All images:"
          docker images