name: Deploy Application

on:
  push:
    branches:
      - 99-realease-branch-via-aws

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: lucatum/nodejs-app-aws-backend:latest
      
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: lucatum/nodejs-app-aws-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Pull backend image
        run: docker pull lucatum/nodejs-app-aws-backend:latest
      
      - name: Pull frontend image
        run: docker pull lucatum/nodejs-app-aws-frontend:latest
      
      - name: Stop and remove existing containers
        run: |
          docker stop nodejs-app-backend nodejs-app-frontend || true
          docker rm nodejs-app-backend nodejs-app-frontend || true
      
      - name: Run backend container
        run: |
          docker run -d --name nodejs-app-backend \
            -p 3001:3001 \
            -e MONGO_URL=${{ secrets.MONGO_URL }} \
            lucatum/nodejs-app-aws-backend:latest
      
      - name: Run frontend container
        run: |
          docker run -d --name nodejs-app-frontend \
            -p 80:80 \
            lucatum/nodejs-app-aws-frontend:latest
      
      - name: Cleanup old images
        run: docker image prune -af