name: Daily Database Backup

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

env:
  MONGO_USER: ${{ secrets.MONGO_USER }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  MONGO_HOST: ${{ secrets.MONGO_HOST }}
  MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MongoDB tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb-org-tools

      - name: Create backup script
        run: |
          cat << EOF > backup.sh
          #!/bin/bash
          set -e
          
          # Construct the MongoDB URI
          uri="mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_DATABASE}"
          
          # Backup directory
          backupDir="./backups/${MONGO_DATABASE}-backup-\$(date +%Y%m%d-%H%M%S)"
          
          # Perform backup
          echo "Performing backup..."
          if ! mongodump --uri="\$uri" --out="\$backupDir"; then
            echo "Error: MongoDB backup failed"
            exit 1
          fi
          
          echo "Backup completed successfully."
          EOF
          
          chmod +x backup.sh

      - name: Run backup
        run: |
          ./backup.sh
        shell: bash

      - name: Upload backup to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: database-backup
          path: ./backups
          retention-days: 7  # Adjust as needed

      - name: Cleanup old backups
        run: rm -rf ./backups